### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ddurdle** [mk-fg/onedrive-fuse-fs#2]
I'm on Linux (Debian flavour).  I use FUSE a lot already for encfs, google, dropbox etc.

I've been using the onedrive-cli for awhile.  Tried installing and using this.  There was no issue with setting it up, but when I try to mount the drive, it just sits there.  I've tried on two systems.  Same result.  I'll sit there for hours.

Is there a debug or logging to check on things.  onedrivecli is working, I just can't get the FUSE wrapper working.

**Comment by mk-fg** [comment]
No idea if still works, haven't used it pretty much since I wrote it (and didn't find any use for it).

I think fuse.py (which is used here to interact with fuse) has "debug" option to at least print what happens, and maybe errors too? I dunno.
And there's --debug option in onedrivefs script itself.
You'd probably also want to use some "run in the foreground" switch with those.

**Comment by mk-fg** [comment]
I know it's a bit necro, and you've probably moved on, but as I did had this notification marked, randomly decided to check on it...

And the thing still "just works" for me, surprisingly.

Furthermore, --debug switch which I suggested above seem to provide quite a lot of comprehensive info, e.g.::

```
fraggod@malediction:-hatch/onedrive-fuse-fs% ./onedrivefs --debug /mnt/tmp
DEBUG:root:FS options: {'api_cache_scale': 1.0, 'api_cache': True}; FUSE: {'foreground': True}
DEBUG:root:-> init / ()
DEBUG:root:<- init None
DEBUG:root:-> getattr / (None,)
DEBUG:onedrive.api_v5:Using "requests" module version: '2.6.0'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): apis.live.net
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive?access_token=... HTTP/1.1" 401 98
DEBUG:onedrive.api_v5:Refreshing access_token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): login.live.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth20_token.srf HTTP/1.1" 200 1446
DEBUG:onedrive.conf:Updating configuration file ('/home/fraggod/.lcrc')
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive?access_token=... HTTP/1.1" 200 316
DEBUG:iso8601.iso8601:Parsed 2015-03-12T09:43:35+0000 into {'tz_sign': u'+', 'second_fraction': None, 'hour': u'09', 'daydash': u'12', 'tz_hour': u'00', 'month': None, 'timezone': u'+0000', 'second': u'35', 'tz_minute': u'00', 'year': u'2015', 'separator': u'T', 'monthdash': u'03', 'day': None, 'minute': u'43'} with default timezone <iso8601.iso8601.Utc object at 0xb69293ac>
DEBUG:iso8601.iso8601:Got u'00' for 'tz_hour' with default None
DEBUG:iso8601.iso8601:Got u'00' for 'tz_minute' with default None
DEBUG:iso8601.iso8601:Got u'2015' for 'year' with default None
DEBUG:iso8601.iso8601:Got u'03' for 'monthdash' with default 1
DEBUG:iso8601.iso8601:Got 3 for 'month' with default 3
DEBUG:iso8601.iso8601:Got u'12' for 'daydash' with default 1
DEBUG:iso8601.iso8601:Got 12 for 'day' with default 12
DEBUG:iso8601.iso8601:Got u'09' for 'hour' with default None
DEBUG:iso8601.iso8601:Got u'43' for 'minute' with default None
DEBUG:iso8601.iso8601:Got u'35' for 'second' with default None
DEBUG:root:<- getattr {u'st_mtime': 1426153415, u'st_size': 4523963956L, u'st_nlink': 2, u'st_mode': 16877}
DEBUG:root:-> opendir / ()
DEBUG:root:<- opendir 0
DEBUG:root:-> readdir / (0L,)
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive/files?access_token=... HTTP/1.1" 200 1656
DEBUG:root:<- readdir [u'.', u'..', u'data', u'Documents', u'me', u'Pics', u'tmp', u'path%with%20percents.txt', u'README.md', u'test.txt', u'zerofile', u'\u4e2d\u6587.txt']
DEBUG:root:-> getattr /data (None,)
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive/files?access_token=...&limit=500 HTTP/1.1" 200 1671
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/folder....?access_token=... HTTP/1.1" 200 385
DEBUG:iso8601.iso8601:Parsed 2014-04-06T00:24:47+0000 into {'tz_sign': u'+', 'second_fraction': None, 'hour': u'00', 'daydash': u'06', 'tz_hour': u'00', 'month': None, 'timezone': u'+0000', 'second': u'47', 'tz_minute': u'00', 'year': u'2014', 'separator': u'T', 'monthdash': u'04', 'day': None, 'minute': u'24'} with default timezone <iso8601.iso8601.Utc object at 0xb69293ac>
DEBUG:iso8601.iso8601:Got u'00' for 'tz_hour' with default None
DEBUG:iso8601.iso8601:Got u'00' for 'tz_minute' with default None
DEBUG:iso8601.iso8601:Got u'2014' for 'year' with default None
DEBUG:iso8601.iso8601:Got u'04' for 'monthdash' with default 1
DEBUG:iso8601.iso8601:Got 4 for 'month' with default 4
DEBUG:iso8601.iso8601:Got u'06' for 'daydash' with default 1
DEBUG:iso8601.iso8601:Got 6 for 'day' with default 6
DEBUG:iso8601.iso8601:Got u'00' for 'hour' with default None
DEBUG:iso8601.iso8601:Got u'24' for 'minute' with default None
DEBUG:iso8601.iso8601:Got u'47' for 'second' with default None
DEBUG:root:<- getattr {u'st_mtime': 1396743887, u'st_size': 3951779471L, u'st_nlink': 2, u'st_mode': 16877}
DEBUG:root:-> getattr /Documents (None,)
...
```

So I wonder if you did e.g. run `onedrivefs /some/path`, it mounted the thing, and "just sat there" waiting for requests from FUSE layer.
And in case it's `ls /some/path` commands that are hanging, that --debug switch should probably help.

Didn't really expect it to work on the first try even for me, but here we go.

**Comment by ddurdle** [comment]
durdle@t420-ssd [58C] [] ~ $ ./onedrivefs --debug /mnt/disk1
DEBUG:root:FS options: {'api_cache_scale': 1.0, 'api_cache': True}; FUSE: {'foreground': True}
DEBUG:root:-> init / ()
DEBUG:root:<- init None
DEBUG:root:-> getattr /.Trash (None,)
DEBUG:onedrive.api_v5:Using "requests" module version: '2.6.0'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): apis.live.net
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive/files?access_token=*REMOVE* HTTP/1.1" 401 98
DEBUG:onedrive.api_v5:Refreshing access_token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): login.live.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth20_token.srf HTTP/1.1" 200 1422
DEBUG:onedrive.conf:Updating configuration file ('/home/durdle/.lcrc')
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive/files?access_token=*REMOVE* HTTP/1.1" 200 6707
DEBUG:root:<- getattr '[Unhandled Exception]'
DEBUG:root:-> getattr /.Trash-1000 (None,)
DEBUG:requests.packages.urllib3.connectionpool:"GET /v5.0/me/skydrive/files?access_token=*REMOVE* HTTP/1.1" 200 6704
DEBUG:root:<- getattr '[Unhandled Exception]'

To prove onedrive-cli works....
durdle@t420-ssd [59C] [] ~ $ onedrive-cli info
client_updated_time: 2014-10-31T13:03:45+0000
comments_count: 0
comments_enabled: False
count: 48
created_time: None
description: 
from:
  id: None
  name: None
id: folder.*REMOVE*
is_embeddable: False
link: https://onedrive.live.com?cid=*REMOVE*
name: SkyDrive
parent_id: None
shared_with:
  access: Just me
size: 3396502191905
type: folder
updated_time: 2015-04-03T14:08:04+0000
upload_location: https://apis.live.net/v5.0/folder.*REMOVE*/files/

**Comment by ddurdle** [comment]
If I run as root...
t420-ssd durdle # onedrivefs --debug /mnt/disk1
DEBUG:root:FS options: {'api_cache_scale': 1.0, 'api_cache': True}; FUSE: {'foreground': True}
DEBUG:root:-> init / ()
DEBUG:root:<- init None

**Comment by mk-fg** [comment]
Running as root shouldn't be necessary, but above --debug output clearly shows that something does `DEBUG:root:-> getattr /.Trash (None,)` that ends up throwing some exception, probably due to something like http-400, as OneDrive doesn't allow names to start with "." iirc.
"something" that does that getattr is probably desktop environment (like GNOME).

Guess such errors from the API should be handled, weird that they aren't, will check.

**Comment by mk-fg** [comment]
Checked, apparently `DEBUG:root:<- getattr '[Unhandled Exception]'` works for me as ENOENT, so probably should work for you in the same way too.

So, again, if the issue seem to be:

    There was no issue with setting it up, but when I try to mount the drive, it just sits there.

This seem to be the expected result - process just runs in the foreground until you stop it.
Did you try doing e.g. "ls" on that path from different shell?

**Comment by ddurdle** [comment]
Ah yes, it does work lol
OneDriveFS     10768875520 3323572511 3323572511  50% /mnt/disk1

I tried doing a ls on the mount point before and it wasn't returning.  Now that I have debug on, I can see it makes a web call for each file+directory within root, so takes a while on a root with 50 files/directories.  I let it run while I watched debug.  It finally returned the list of contents.  Perfect.

This will be handy.

**Comment by mk-fg** [comment]
I think it should be way faster if it was simply opendir(2) + readdir(2) - that's just a single onedrive call, as you can probably see in traces, but on most distros and configurations, "ls" is aliased to something like `ls --color=auto --group-directories-first`, which it does in only way POSIX fs semantics allow:

* stat on specified dir
* opendir
* readdir
* stat on **each name in that dir**, sequentially
* getxattr on **each name in that dir**, sequentially

I.e. readdir(2) there can't return attributes for each file/dir (and whether it's a file or dir at all), just a list of names, and for `--group-directories-first` ls needs mode for each name, and for `--color=auto` I think it also checks xattrs (to e.g. mark stuff with posix capabilities red).

Furthermore, old API doesn't even have anything like paths, only id's linked to each other, with "name" attribute attached to each, so "ls path1/path2/path3" will do 3 requests just to "resolve" that path (list root, find "path1" there, list path1-id, find "path2" there, etc).

Stuff can be cached, e.g. whatever readdir returns (which is later queried by stat), and that's what I started implementing with "CacheLRU" and "PerPathCache" classes, but then you run into a problem of its invalidation, it gets complicated fast.
Not anywhere near impossible, just something should be implemented by someone who cares, then I think it can work, at least as long as you have only one client messing with the remote stuff.

So I guess two points I'd like to make here:

* To make it faster, do `unalias ls` and avoid anything that fancy.
* To make it even faster, stop using OneDrive through POSIX FS interface entirely, which it does not implement (or maps to) natively, hence the inherent inefficiency/complexity/bugs of such translation.

**Comment by pashazz** [comment]
```
sudo onedrivefs  --debug /mnt/onedrive                                                                                                                   
DEBUG:root:FS options: {'api_cache_scale': 1.0, 'api_cache': True}; FUSE: {'foreground': True}
DEBUG:root:-> init / ()
DEBUG:root:<- init None
```

`onedrive-cli ls/get/put` works like a charm

**Comment by mk-fg** [comment]
@pashazz
Looks like command you ran worked, as there's no error, guess it's just not obvious that it doesn't fork itself into background by default.

**Comment by mk-fg** [comment]
By the way, don't think you need "sudo" there.

**Comment by mk-fg** [comment]
Changed default behavior (as of bbd6a93) to go into background, but --debug now implies --foreground (as otherwise there will be no output), so be sure to drop that option if you want it to fork out from console.
Should do the same thing with the command you've used - i.e. go up to init and wait/serve requests to fs from there.

**Comment by pashazz** [comment]
Thanks!

**Comment by pashazz** [comment]
```
 onedrivefs ~/.lcrc /mnt/onedrive                                                                                                                                             
/usr/bin/env: python22: No such file or directory
```

Fix it please. Of course I changed the first line for myself.

**Comment by mk-fg** [comment]
Uhhh.... it has "python2" in there - https://github.com/mk-fg/onedrive-fuse-fs/blob/master/onedrivefs#L1

Not sure what changed it to "python22" for you, maybe some patch you've applied on top?

**Comment by pashazz** [comment]
May be. I use Arch...apparently they f**ked up the pkgbuild :D

**Comment by mk-fg** [comment]
Apparently so - https://aur.archlinux.org/packages/on/onedrive-fuse-fs-git/PKGBUILD - sed line there does that, as I've replaced python with python2 in the repo (it's the right thing to do).

I think I've been bitten by not including that "$" in regexp wrt python shebangs a few times already, seem to be an easy mistake to make. Should be easy to fix though.
