### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by czipperz** [mk-fg/onedrive-fuse-fs#3]
You use

    % asdf

to show what commands to run as a non-super user. This should be

    $ asdf

**Comment by mk-fg** [comment]
Should it be, really?
In my shell (and I think zsh in general) it's `% asdf` (and `# asdf` for root).
Also, "console" syntaxes (e.g. in pygments) work with %, so it's apparently conventional enough to make it there.

**Comment by czipperz** [comment]
I use zsh, yes, but bash is the default terminal in most unix operating systems. Please use the syntax that is most common. Its just convention

**Comment by mk-fg** [comment]
You probably mean "default shell", not terminal, which I think is indeed true.

Personally I like % more, and use these everywhere, so would prefer to keep these, unless it's really bad or confusing, which I'm not convinced it is.
And given that a lot of people actually use zsh as an interactive shell, which you seem to confirm, maybe it's time to change that stupid convention, or at least make it weaker.

**Comment by czipperz** [comment]
Alright sounds fine. Maybe ill start doing that too.
