### ISSUE TITLE
Use official onedrive-sdk-python

### ISSUE THREAD

**Issue by pkuczynski** [mk-fg/onedrive-fuse-fs#5]
python-onedrive is completely obsoleted by official onedrive-sdk-python. Could you please upgrade to this new module?

https://github.com/OneDrive/onedrive-sdk-python

**Comment by mk-fg** [comment]
I can, and it will be the right thing to do, but I don't use OneDrive myself for a while now, so don't use or need the script either, so don't want to put an effort to check out new API module and update the code.
Furthermore,  code that maintainers don't use themselves usually is a recipie for disaster, so it won't work anyway.

Script is fairly trivial though, with most complex bits being hastily slapped-on caching, which needs changes anyway, so I feel best course of action here would be for anyone actually using or caring about the thing to rewrite it as a separate project.
I'd be happy to put a "Use this one instead" notice here and link to it.

**Comment by pkuczynski** [comment]
I understand your rationale, but believe this issue should be kept open. Otherwise how people would know what's still to be done? I guess you could also add the note in the README.md that this repo looks for maintainer... :)

**Comment by mk-fg** [comment]
Yeah, guess only mention that old API is used is `old API that python-onedrive module uses` in Limitations section. It can be made way more clear than that, will update.

Don't think it's worth "looking for new maintainer" for code that's like 100 trivial lines, as I expect it'll be way faster for someone to just look over what they do and re-implement them entirely than to adapt to existing code style/logic, and probably not even that (as it's fairly obvious how posix fs api works, and new onedrive api probably can be mapped to these calls in a different - more efficient - way).

Will update the README in similar fashion as I did in python-onedrive, thanks for pointing that out.
